name: Push to GitLab
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Push to GitLab
        run: |
          git remote add gitlab git@gitlab.com:whgpngudsd-group/sthaophr.git
          git push --mirror gitlab
