name: Gitlab Mirroring
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  to_gitlab:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # حدثناه للإصدار v4 لأنه يدعم Node 20/24 تلقائياً
        with:
          fetch-depth: 0

      - name: Mirroring to GitLab
        uses: wangyucode/git-mirror-action@v1.0.1  # استخدمنا أداة أحدث
        with:
          target_repo_url: git@gitlab.com:whgpngudsd-ux/sthaophr.git
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
