name: Deploy to GitLab

on: [push]

jobs:
  to_gitlab:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Mirror to GitLab
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: git@gitlab.com:whgpngudsd/sthaophr.git
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
